### ISSUE TITLE
Webpack - Fails in production mode with Terser

### ISSUE THREAD

**Issue by jakesdavis** [IRCraziestTaxi/ts-simple-nameof#11]
Issue:
 Using nameof throws error `ts-simple-nameof: Invalid function.`

Issue is with how the parser works. 

`if (fnStr.startsWith("function (")) {` will not capture functions with format 
`function(x) { return x.value }` 
Lack of space between function and left parentheses.

Resolution.
Can be resolved by adding the extra condition.

I can raise a PR for this if required.

**Comment by IRCraziestTaxi** [comment]
@jakesdavis Thanks for the PR and apologies for not chiming in on this sooner.

I added a comment to the PR. Will be happy to merge and publish new version so this issue can be closed when that comment is resolved.

**Comment by IRCraziestTaxi** [comment]
Fixed and published in version 1.2.1.
